export const APP_NAME = 'AUTH'

export const ACTION_TYPES = {
  SET_TOKEN: `${APP_NAME}/SET_TOKEN`,
  SET_CURRENT_USER: `${APP_NAME}/SET_CURRENT_USER`,
  UNSET_CURRENT_USER: `${APP_NAME}/UNSET_CURRENT_USER`,
}