# Generated by Django 3.1.2 on 2022-05-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20220409_1107"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="modified",
        ),
    ]
