# Generated by Django 3.1.2 on 2022-05-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountant", "0004_auto_20220529_2143"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_correction",
            field=models.BooleanField(default=False),
        ),
    ]
