# Generated by Django 3.1.2 on 2022-06-01 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountant", "0006_transaction_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="type",
            new_name="enum_type",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="type",
            new_name="enum_type",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accountant.category",
            ),
        ),
    ]
