# Generated by Django 3.1.2 on 2022-06-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountant", "0007_auto_20220601_0933"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ("date",)},
        ),
    ]
