# Generated by Django 3.1.2 on 2022-06-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountant", "0008_auto_20220607_1502"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.FloatField(default=0),
        ),
    ]
