# Generated by Django 3.1.2 on 2022-06-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountant", "0010_auto_20220607_2053"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ("-date", "-created")},
        ),
    ]
