# Generated by Django 4.0.6 on 2022-07-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountant", "0013_auto_20220629_1430"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("title", "user", "enum_type"), name="unique_title"
            ),
        ),
    ]
