# Generated by Django 4.0.6 on 2022-07-12 16:17

from django.db import migrations, models

from apps.accountant.services import generate_random_hex


class Migration(migrations.Migration):

    dependencies = [
        ("accountant", "0014_category_unique_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(default=generate_random_hex, max_length=7),
        ),
    ]
