# Generated by Django 4.0.6 on 2022-07-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0015_category_color'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('color', 'user', 'enum_type'), name='unique_color'),
        ),
    ]
